name: Délégation des Compétitions en Informatique de l'ÉTS
markdown: redcarpet
pygments: true
permalink: pretty
safe: true
lsi: false

# exclude some files we don't want to leak
exclude: [ 'README.md', 'CNAME' ]
