name: "Délégation des Compétitions en Informatique de l'ÉTS"
markdown: kramdown
highlighter: rouge
permalink: pretty
safe: true
url: "http://dciets.com"
lsi: false

# exclude some files we don't want to leak
exclude: [ 'README.md', 'CNAME' ]
